packages:
  - playground
  - docs
  - packages/*
  - examples/*
  - app/*
catalog:
  '@ant-design/icons': ^5.6.1
  '@ant-design/pro-components': ^2.8.6
  '@antfu/eslint-config': ^4.2.1
  '@antfu/ni': ^23.3.1
  '@eslint-react/eslint-plugin': ^1.35.0
  '@iconify-json/svg-spinners': ^1.2.2
  '@shikijs/vitepress-twoslash': ^2.3.2
  '@types/node': ^22.13.4
  '@types/react': ^19.0.10
  '@types/react-dom': ^19.0.4
  '@vitejs/plugin-react': ^4.3.4
  ahooks: ^3.8.4
  antd: ^5.24.4
  bumpp: ^10.0.3
  dayjs: ^1.11.13
  eslint: ^9.20.1
  eslint-plugin-react-hooks: ^5.2.0
  eslint-plugin-react-refresh: ^0.4.19
  lint-staged: ^15.4.3
  motion: ^12.5.0
  react: ^18.3.1
  react-dom: ^18.3.1
  react-hook-form: ^7.54.2
  react-i18next: ^14.1.2
  react-number-format: ^5.4.3
  react-router-dom: ^7.3.0
  sass: ^1.72.0
  simple-git-hooks: ^2.11.1
  tsx: ^4.19.2
  typescript: ^5.7.3
  unbuild: ^3.3.1
  unocss: ^65.5.0
  unplugin-auto-import: ^19.1.0
  vite: ^6.2.2
  vite-tsconfig-paths: ^5.1.4
  vitepress: ^2.0.0-alpha.2
  vitepress-plugin-group-icons: ^1.3.5
  vitest: ^3.0.5
  zustand: ^5.0.3
